version: '3'
services:
  database:
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rezepte_user
      MYSQL_DATABASE: rezepte_db
      MYSQL_USER: rezepte_user
      MYSQL_PASSWORD: rezepte_user

volumes:
  database-data:
